// Mocks generated by Mockito from annotations
// in piggybank/test/backup/import_tag_association_bug_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:piggybank/models/budget.dart' as _i4;
import 'package:piggybank/models/category-type.dart' as _i6;
import 'package:piggybank/models/category.dart' as _i5;
import 'package:piggybank/models/profile.dart' as _i11;
import 'package:piggybank/models/record-tag-association.dart' as _i8;
import 'package:piggybank/models/record.dart' as _i7;
import 'package:piggybank/models/recurrent-record-pattern.dart' as _i9;
import 'package:piggybank/models/wallet.dart' as _i10;
import 'package:piggybank/services/database/database-interface.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DatabaseInterface].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseInterface extends _i1.Mock implements _i2.DatabaseInterface {
  MockDatabaseInterface() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Budget>> getBudgets({int? profileId}) =>
      (super.noSuchMethod(
        Invocation.method(#getBudgets, [], {#profileId: profileId}),
        returnValue: _i3.Future<List<_i4.Budget>>.value(<_i4.Budget>[]),
      ) as _i3.Future<List<_i4.Budget>>);

  @override
  _i3.Future<int> addBudget(_i4.Budget? budget) => (super.noSuchMethod(
    Invocation.method(#addBudget, [budget]),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateBudget(_i4.Budget? budget) => (super.noSuchMethod(
    Invocation.method(#updateBudget, [budget]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteBudget(int? id) => (super.noSuchMethod(
    Invocation.method(#deleteBudget, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> archiveBudget(int? id, bool? isArchived) =>
      (super.noSuchMethod(
        Invocation.method(#archiveBudget, [id, isArchived]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.Category?>> getAllCategories() => (super.noSuchMethod(
    Invocation.method(#getAllCategories, []),
    returnValue: _i3.Future<List<_i5.Category?>>.value(<_i5.Category?>[]),
  ) as _i3.Future<List<_i5.Category?>>);

  @override
  _i3.Future<List<_i5.Category?>> getCategoriesByType(
    _i6.CategoryType? categoryType,
  ) => (super.noSuchMethod(
    Invocation.method(#getCategoriesByType, [categoryType]),
    returnValue: _i3.Future<List<_i5.Category?>>.value(<_i5.Category?>[]),
  ) as _i3.Future<List<_i5.Category?>>);

  @override
  _i3.Future<_i5.Category?> getCategory(
    String? categoryName,
    _i6.CategoryType? categoryType,
  ) => (super.noSuchMethod(
    Invocation.method(#getCategory, [categoryName, categoryType]),
    returnValue: _i3.Future<_i5.Category?>.value(),
  ) as _i3.Future<_i5.Category?>);

  @override
  _i3.Future<int> addCategory(_i5.Category? category) => (super.noSuchMethod(
    Invocation.method(#addCategory, [category]),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Future<int> updateCategory(
    String? existingCategoryName,
    _i6.CategoryType? existingCategoryType,
    _i5.Category? updatedCategory,
  ) => (super.noSuchMethod(
    Invocation.method(#updateCategory, [
      existingCategoryName,
      existingCategoryType,
      updatedCategory,
    ]),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Future<void> deleteCategory(
    String? name,
    _i6.CategoryType? categoryType,
  ) => (super.noSuchMethod(
    Invocation.method(#deleteCategory, [name, categoryType]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> archiveCategory(
    String? categoryName,
    _i6.CategoryType? categoryType,
    bool? isArchived,
  ) => (super.noSuchMethod(
    Invocation.method(#archiveCategory, [
      categoryName,
      categoryType,
      isArchived,
    ]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> resetCategoryOrderIndexes(
    List<_i5.Category>? orderedCategories,
  ) => (super.noSuchMethod(
    Invocation.method(#resetCategoryOrderIndexes, [orderedCategories]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<_i7.Record?> getRecordById(int? id) => (super.noSuchMethod(
    Invocation.method(#getRecordById, [id]),
    returnValue: _i3.Future<_i7.Record?>.value(),
  ) as _i3.Future<_i7.Record?>);

  @override
  _i3.Future<void> deleteRecordById(int? id) => (super.noSuchMethod(
    Invocation.method(#deleteRecordById, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRecordsInBatch(List<int>? ids) => (super.noSuchMethod(
    Invocation.method(#deleteRecordsInBatch, [ids]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<int> addRecord(_i7.Record? record) => (super.noSuchMethod(
    Invocation.method(#addRecord, [record]),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Future<void> addRecordsInBatch(List<_i7.Record?>? records) =>
      (super.noSuchMethod(
        Invocation.method(#addRecordsInBatch, [records]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addRecordsInBatchNoDuplicateCheck(
    List<_i7.Record?>? records,
  ) => (super.noSuchMethod(
    Invocation.method(#addRecordsInBatchNoDuplicateCheck, [records]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<int?> updateRecordById(int? recordId, _i7.Record? newRecord) =>
      (super.noSuchMethod(
        Invocation.method(#updateRecordById, [recordId, newRecord]),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  _i3.Future<void> updateRecordWalletInBatch(List<int>? ids, int? walletId) =>
      (super.noSuchMethod(
        Invocation.method(#updateRecordWalletInBatch, [ids, walletId]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> duplicateRecordsInBatch(List<int>? ids) =>
      (super.noSuchMethod(
        Invocation.method(#duplicateRecordsInBatch, [ids]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<DateTime?> getDateTimeFirstRecord() => (super.noSuchMethod(
    Invocation.method(#getDateTimeFirstRecord, []),
    returnValue: _i3.Future<DateTime?>.value(),
  ) as _i3.Future<DateTime?>);

  @override
  _i3.Future<List<_i7.Record?>> getAllRecords({int? profileId}) =>
      (super.noSuchMethod(
        Invocation.method(#getAllRecords, [], {#profileId: profileId}),
        returnValue: _i3.Future<List<_i7.Record?>>.value(<_i7.Record?>[]),
      ) as _i3.Future<List<_i7.Record?>>);

  @override
  _i3.Future<int> getCountRecords() => (super.noSuchMethod(
    Invocation.method(#getCountRecords, []),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Future<List<_i7.Record?>> getAllRecordsInInterval(
    DateTime? from,
    DateTime? to, {
    int? profileId,
  }) => (super.noSuchMethod(
    Invocation.method(
      #getAllRecordsInInterval,
      [from, to],
      {#profileId: profileId},
    ),
    returnValue: _i3.Future<List<_i7.Record?>>.value(<_i7.Record?>[]),
  ) as _i3.Future<List<_i7.Record?>>);

  @override
  _i3.Future<_i7.Record?> getMatchingRecord(_i7.Record? record) =>
      (super.noSuchMethod(
        Invocation.method(#getMatchingRecord, [record]),
        returnValue: _i3.Future<_i7.Record?>.value(),
      ) as _i3.Future<_i7.Record?>);

  @override
  _i3.Future<void> deleteFutureRecordsByPatternId(
    String? recurrentPatternId,
    DateTime? startingTime,
  ) => (super.noSuchMethod(
    Invocation.method(#deleteFutureRecordsByPatternId, [
      recurrentPatternId,
      startingTime,
    ]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<List<String>> suggestedRecordTitles(
    String? search,
    String? categoryName,
  ) => (super.noSuchMethod(
    Invocation.method(#suggestedRecordTitles, [search, categoryName]),
    returnValue: _i3.Future<List<String>>.value(<String>[]),
  ) as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> getTagsForRecord(int? recordId) =>
      (super.noSuchMethod(
        Invocation.method(#getTagsForRecord, [recordId]),
        returnValue: _i3.Future<List<String>>.value(<String>[]),
      ) as _i3.Future<List<String>>);

  @override
  _i3.Future<Set<String>> getAllTags() => (super.noSuchMethod(
    Invocation.method(#getAllTags, []),
    returnValue: _i3.Future<Set<String>>.value(<String>{}),
  ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<Set<String>> getRecentlyUsedTags() => (super.noSuchMethod(
    Invocation.method(#getRecentlyUsedTags, []),
    returnValue: _i3.Future<Set<String>>.value(<String>{}),
  ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<Set<String>> getMostUsedTagsForCategory(
    String? categoryName,
    _i6.CategoryType? categoryType,
  ) => (super.noSuchMethod(
    Invocation.method(#getMostUsedTagsForCategory, [
      categoryName,
      categoryType,
    ]),
    returnValue: _i3.Future<Set<String>>.value(<String>{}),
  ) as _i3.Future<Set<String>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> getAggregatedRecordsByTagInInterval(
    DateTime? from,
    DateTime? to,
  ) => (super.noSuchMethod(
    Invocation.method(#getAggregatedRecordsByTagInInterval, [from, to]),
    returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
      <Map<String, dynamic>>[],
    ),
  ) as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<_i8.RecordTagAssociation>> getAllRecordTagAssociations() =>
      (super.noSuchMethod(
        Invocation.method(#getAllRecordTagAssociations, []),
        returnValue: _i3.Future<List<_i8.RecordTagAssociation>>.value(
          <_i8.RecordTagAssociation>[],
        ),
      ) as _i3.Future<List<_i8.RecordTagAssociation>>);

  @override
  _i3.Future<void> renameTag(String? old, String? newTag) =>
      (super.noSuchMethod(
        Invocation.method(#renameTag, [old, newTag]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteTag(String? tagToDelete) => (super.noSuchMethod(
    Invocation.method(#deleteTag, [tagToDelete]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i9.RecurrentRecordPattern>> getRecurrentRecordPatterns({
    int? profileId,
  }) => (super.noSuchMethod(
    Invocation.method(#getRecurrentRecordPatterns, [], {#profileId: profileId}),
    returnValue: _i3.Future<List<_i9.RecurrentRecordPattern>>.value(
      <_i9.RecurrentRecordPattern>[],
    ),
  ) as _i3.Future<List<_i9.RecurrentRecordPattern>>);

  @override
  _i3.Future<_i9.RecurrentRecordPattern?> getRecurrentRecordPattern(
    String? recurrentPatternId,
  ) => (super.noSuchMethod(
    Invocation.method(#getRecurrentRecordPattern, [recurrentPatternId]),
    returnValue: _i3.Future<_i9.RecurrentRecordPattern?>.value(),
  ) as _i3.Future<_i9.RecurrentRecordPattern?>);

  @override
  _i3.Future<void> addRecurrentRecordPattern(
    _i9.RecurrentRecordPattern? recordPattern,
  ) => (super.noSuchMethod(
    Invocation.method(#addRecurrentRecordPattern, [recordPattern]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteRecurrentRecordPatternById(
    String? recurrentPatternId,
  ) => (super.noSuchMethod(
    Invocation.method(#deleteRecurrentRecordPatternById, [recurrentPatternId]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateRecordPatternById(
    String? recurrentPatternId,
    _i9.RecurrentRecordPattern? pattern,
  ) => (super.noSuchMethod(
    Invocation.method(#updateRecordPatternById, [recurrentPatternId, pattern]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i10.Wallet>> getAllWallets({int? profileId}) =>
      (super.noSuchMethod(
        Invocation.method(#getAllWallets, [], {#profileId: profileId}),
        returnValue: _i3.Future<List<_i10.Wallet>>.value(<_i10.Wallet>[]),
      ) as _i3.Future<List<_i10.Wallet>>);

  @override
  _i3.Future<List<_i10.Wallet>> getWalletsBalanceAsOf(
    DateTime? asOfDate, {
    int? profileId,
  }) => (super.noSuchMethod(
    Invocation.method(
      #getWalletsBalanceAsOf,
      [asOfDate],
      {#profileId: profileId},
    ),
    returnValue: _i3.Future<List<_i10.Wallet>>.value(<_i10.Wallet>[]),
  ) as _i3.Future<List<_i10.Wallet>>);

  @override
  _i3.Future<List<_i11.Profile>> getAllProfiles() => (super.noSuchMethod(
    Invocation.method(#getAllProfiles, []),
    returnValue: _i3.Future<List<_i11.Profile>>.value(<_i11.Profile>[]),
  ) as _i3.Future<List<_i11.Profile>>);

  @override
  _i3.Future<_i11.Profile?> getDefaultProfile() => (super.noSuchMethod(
    Invocation.method(#getDefaultProfile, []),
    returnValue: _i3.Future<_i11.Profile?>.value(),
  ) as _i3.Future<_i11.Profile?>);

  @override
  _i3.Future<void> setDefaultProfile(int? id) => (super.noSuchMethod(
    Invocation.method(#setDefaultProfile, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<_i11.Profile?> getProfileById(int? id) => (super.noSuchMethod(
    Invocation.method(#getProfileById, [id]),
    returnValue: _i3.Future<_i11.Profile?>.value(),
  ) as _i3.Future<_i11.Profile?>);

  @override
  _i3.Future<int> addProfile(_i11.Profile? profile) => (super.noSuchMethod(
    Invocation.method(#addProfile, [profile]),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateProfile(_i11.Profile? profile) => (super.noSuchMethod(
    Invocation.method(#updateProfile, [profile]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProfileAndRecords(int? id) => (super.noSuchMethod(
    Invocation.method(#deleteProfileAndRecords, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<_i10.Wallet?> getWalletById(int? id) => (super.noSuchMethod(
    Invocation.method(#getWalletById, [id]),
    returnValue: _i3.Future<_i10.Wallet?>.value(),
  ) as _i3.Future<_i10.Wallet?>);

  @override
  _i3.Future<_i10.Wallet?> getWalletByName(String? name, int? profileId) =>
      (super.noSuchMethod(
        Invocation.method(#getWalletByName, [name, profileId]),
        returnValue: _i3.Future<_i10.Wallet?>.value(),
      ) as _i3.Future<_i10.Wallet?>);

  @override
  _i3.Future<int> addWallet(_i10.Wallet? wallet) => (super.noSuchMethod(
    Invocation.method(#addWallet, [wallet]),
    returnValue: _i3.Future<int>.value(0),
  ) as _i3.Future<int>);

  @override
  _i3.Future<void> updateWallet(int? id, _i10.Wallet? wallet) =>
      (super.noSuchMethod(
        Invocation.method(#updateWallet, [id, wallet]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteWalletAndRecords(int? id) => (super.noSuchMethod(
    Invocation.method(#deleteWalletAndRecords, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> moveRecordsToWallet(int? fromId, int? toId) =>
      (super.noSuchMethod(
        Invocation.method(#moveRecordsToWallet, [fromId, toId]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> archiveWallet(int? id, bool? isArchived) =>
      (super.noSuchMethod(
        Invocation.method(#archiveWallet, [id, isArchived]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> setDefaultWallet(int? id) => (super.noSuchMethod(
    Invocation.method(#setDefaultWallet, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<void> setPredefinedWallet(int? id) => (super.noSuchMethod(
    Invocation.method(#setPredefinedWallet, [id]),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);

  @override
  _i3.Future<_i10.Wallet?> getPredefinedWallet() => (super.noSuchMethod(
    Invocation.method(#getPredefinedWallet, []),
    returnValue: _i3.Future<_i10.Wallet?>.value(),
  ) as _i3.Future<_i10.Wallet?>);

  @override
  _i3.Future<_i10.Wallet?> getDefaultWallet() => (super.noSuchMethod(
    Invocation.method(#getDefaultWallet, []),
    returnValue: _i3.Future<_i10.Wallet?>.value(),
  ) as _i3.Future<_i10.Wallet?>);

  @override
  _i3.Future<void> resetWalletOrderIndexes(List<_i10.Wallet>? ordered) =>
      (super.noSuchMethod(
        Invocation.method(#resetWalletOrderIndexes, [ordered]),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDatabase() => (super.noSuchMethod(
    Invocation.method(#deleteDatabase, []),
    returnValue: _i3.Future<void>.value(),
    returnValueForMissingStub: _i3.Future<void>.value(),
  ) as _i3.Future<void>);
}
