name: in_app_purchase_android
description: No-op stub for F-Droid builds.
publish_to: none
version: 0.0.1
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter
  in_app_purchase:
    path: ../in_app_purchase
